### ISSUE TITLE
Tensorflow 2.x Support

### ISSUE THREAD

**Issue by sohamm17** [jahnog/tensorflow-32-bits-linux#2]
Does this work for Tensorflow 2.x

**Comment by jahnog** [comment]
Unfortunately no. Starting from version 1.14, tensorflow uses the Intel MKL DNN optimization library that only works in 64 bit systems. So 1.13.2 is the last version that runs in 32 bits.

**Comment by sohamm17** [comment]
Thanks for clarifying. Intel beignet is an OpenCL runtime which still supports 32-bit. But it's not well-supported. So I guess Tensorflow does not work with Intel beignet.
